### ISSUE TITLE
Takes a long time for onScroll to fire

### ISSUE THREAD

**Issue by ghost** [orizens/ngx-infinite-scroll#198] opened 2017-10-28 15:36 UTC
I have

```
<div class="search-results" 
    infiniteScroll 
    [infiniteScrollDistance]="2"
    [infiniteScrollThrottle]="500" 
    (scrolled)="onScroll()">
</div>
```

When I scroll to the bottom, it somtimes takes 4 seconds for onScroll to fire.

I've tried all kinds of values for infiniteScrollDistance. With a high value, it works initially, but after scrolling for a while, the problem is back.

**Comment by orizens** [comment] 2017-10-29 14:23
please share a plunkr that reproduce it.

**Comment by lansana** [comment] 2017-11-17 03:27
I experience this as well. But this does not have to do with the firing of `scrolled`. If you look at the network tab (assuming your `onScroll` makes an HTTP request), you will see that your `onScroll` is always called because the HTTP request is made when it should be, it's just that the request itself takes a few seconds to complete. I have no idea why this happens, I had a [question on SO](https://stackoverflow.com/questions/44388885/angular2-directive-causes-http-response-to-take-long-when-scrolling-with-mousew) about it on a few months back with my own custom infinite scroll directive. Apparently this project has the same bug >.<

It's weird because the lengthy request only happens because it was triggered by this directive, and will never take that long if you do the HTTP call another way, for instance with a button click.

**Comment by orizens** [comment] 2017-11-17 13:53
this infinite scroll is an extract from http://echoesplayer.com - where it works pretty well.

**Comment by adrienverge** [comment] 2017-11-23 21:20
I experience the same problem as @ghost (the original author): whatever `infiniteScrollThrottle` or `infiniteScrollDistance` values, the callback function is called after approximately 2 seconds.

(@lansana I think you don't have the exact same problem.)

Clue 1: When using `[scrollWindow]="false"` and `height: 20rem; overflow: scroll;`, the problem disappears (but this is not a satisfying solution).

Clue 2: Completely removing the throttle in code removes the problem:
```diff
--- node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js
+++ node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js
@@ -311,7 +311,9 @@
  */
 function attachScrollEvent(options) {
     return Observable.fromEvent(options.container, 'scroll')
-        .sampleTime(options.throttleDuration)
+        .do(event => console.warn('received event: ' + event))
         .filter(options.filterBefore)
         .mergeMap(function (ev) { return Observable.of(options.mergeMap(ev)); })
         .subscribe(options.scrollHandler);
```

Clue 3: I tried replacing `sampleTime()` by `debounceTime()` and `throttleTime()`: it does the same "2 seconds delay effect". Only removing it solves the issue.

I tried reproducing the problem using the demo plunker, but couldn't (I even changed versions to use latest software, i.e. Angular 5.0.3 and rxjs 5.2.2).

**Comment by orizens** [comment] 2017-11-27 19:27
without a demo for this bug - it's hard to pinpoint the cause.
did you try reducing the throttle to 20-50?

**Comment by adrienverge** [comment] 2017-11-27 20:16
Hi @orizens, thanks for following this up.

> without a demo for this bug - it's hard to pinpoint the cause.

I agree, and I'm sad I couldn't reproduce this in a plunker although I spent 30 min trying. I guess it's related to other dependencies in my project. I tried various versions of Angular, RxJS, Typescript and ngx-infinite-scroll.

> did you try reducing the throttle to 20-50?

Of course! I even tried 0. The only thing that works is really removing the call to `sampleTime()` in the code.

I also noticed that replacing `.sampleTime(options.throttleDuration)` by any other RxJS function (e.g., `.delay(0)`) results in the same bug. Only completely removing the call to any RxJS function solves the problem.

**Comment by orizens** [comment] 2017-11-28 09:30
it sounds like something in your app its out of zone and enters back after some processing.

**Comment by adrienverge** [comment] 2017-11-28 11:39
Hey Oren,

I'm not sure about that, because `console.warn()` logs *really are* delayed of 2 seconds, i.e. it's not only Angular change detection.

`node_modules/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js`:
```diff
 function attachScrollEvent(options) {
     return Observable.fromEvent(options.container, 'scroll')
+        .do(event => console.warn('I am displayed instantaneously))
         .sampleTime(10)
+        .do(event => console.warn('I am displayed after 2 seconds))
         .filter(options.filterBefore)
```

Another "funny" thing: the problem only happens with a mouse or trackpad. When using keyboard buttons (page down, end, arrows), all `console.warn()` logs are displayed instantaneously and the `(scrolled)=...` callback also.

**Comment by orizens** [comment] 2017-11-28 12:12
interesting - we need to find the cause, as sampleTime does work as expected for other use cases.

**Comment by orizens** [comment] 2018-01-02 11:46
all - please try latest 0.8.0.

**Comment by nupa** [comment] 2018-01-08 12:41
I experienced this issue also on Chrome (OS X), but not in other browsers. Happens still with new 0.8.1. It seems that the problematic part is the sampleTime() as adrienverge found out above. I think the root cause might be this: https://bugs.chromium.org/p/chromium/issues/detail?id=661155

sampleTime() uses timeout and while scrolling - especially rapidly with track pad - the events won't arrive. After the scrolling is stopped, it takes couple of seconds and everything is working again.

I wonder if the semantics of the scroll throttle option could be changed a bit, so that 0 would leave the sampleTime() part out totally?

**Comment by orizens** [comment] 2018-01-08 13:07
you can tryout zero now. 
I'll think of how we can toggle between throttle and sampleTime

**Comment by adrienverge** [comment] 2018-01-08 14:01
Bug still present with versions 0.8.0 and 0.8.1, with or without `[infiniteScrollThrottle]="0"`.

The problem still lies in the call to `sampleTime(options.throttle)`: 
https://github.com/orizens/ngx-infinite-scroll/blob/7880627955765d8d50575f75e5a9a79b4bb8bb85/src/services/scroll-register.ts#L64

**Comment by oskvortsov-bmt** [comment] 2018-02-08 14:32
@orizens maybe if options.throttle 0 or null return without sampleTime?
I tried this solve 
`function attachScrollEvent(options) {
    var obs = Observable.fromEvent(options.container, 'scroll');
    return options.throttle ? obs.sampleTime(options.throttle) : obs;
}`, 
it`s helped me.

**Comment by jcroll** [comment] 2018-02-08 14:55
@orizens I have to admit I'm not sure why you closed this issue.

This is a real bug that directly impacts the functionality of your library [in the most used browser by market share by far](https://www.w3counter.com/globalstats.php).

I understand this is open source and other people can contribute solutions but at least keep the issue open until fixed!

**Comment by orizens** [comment] 2018-02-08 15:18
@jcroll does zero helps?
It seems like this is a bug in chrome.
I'll reopen to allow pr from community

**Comment by oskvortsov-bmt** [comment] 2018-02-08 15:27
@orizens yes, zero not helps.

**Comment by jcroll** [comment] 2018-02-08 15:36
Thanks @orizens. No the zero doesn't help, I believe some of the devs in this thread or zeroing in on it tho.

**Comment by ssleptsov** [comment] 2018-02-09 16:47
Experience same issue. Same HTTP requests that can 30ms, take 2.3 seconds :( 
And this code doesn't helped 
`
const obs = Observable.fromEvent(options.container, 'scroll'); 
  return options.throttle ? obs.throttleTime(options.throttle) : obs; 
`

**Comment by zaikin-andrew** [comment] 2018-02-10 08:45
@orizens Hi guys, I've faced the same trouble :( Any estimation when it can be fixed? Thanks!

**Comment by adrienverge** [comment] 2018-02-10 09:03
I have opened https://github.com/orizens/ngx-infinite-scroll/pull/235, it solves the problem for me when using `[infiniteScrollThrottle]="0"`.

**Comment by AndreaVitale** [comment] 2018-02-20 14:48
Same here. Using `[infiniteScrollThrottle]="0"` as a workaround "solves" the issue.

**Comment by orizens** [comment] 2018-02-21 08:43
@adrienverge thanks - looking at your pr. 
@zaikin-andrew - i'm inspecting possible solutions

**Closed** 2018-02-21 08:55 UTC
Labels: help wanted, investigating, needs more INFO, to-verify

**Comment by adrienverge** [comment] 2018-02-21 08:58
@orizens thanks!

**Comment by orizens** [comment] 2018-02-21 10:37
version 0.8.3 released

**Comment by tfalvo** [comment] 2018-06-18 17:32
Issue still exists with last version of Chrome and even with `[infiniteScrollThrottle]="0"`.

**Comment by tfalvo** [comment] 2018-06-19 07:34
Thanks to this [https://stackoverflow.com/questions/47524205/random-high-content-download-time-in-chrome/47684257#47684257](url), it seems I solved the issue.

I added a `mousewheel` on infinite scroll directive :
 
`
@HostListener('mousewheel')
onMouseWheel() {
}
`

No more slow http request.

**Comment by fabiocarneiro** [comment] 2020-10-25 01:24
I have been struggling a lot with this, without knowing it was the same issue. I am using Angular Elements, and it was behaving properly during the development. When I finished the component, bundled, and started using in my website, it would not scroll.

I thought it was something about angular, about angular elements, about me missing something about how events work with elements, 2 days later, after testing with my own scroll listener and realizing mine would work, I commented out the lines of`sampleTime` if, and it finally started working. 

I also did an experiment of replacing the `sampleTime`, with `throttleTime` and it also works. Was this option already considered?
