### ISSUE TITLE
Opencollective install issues

### ISSUE THREAD

**Issue by spacem** [orizens/ngx-infinite-scroll#266] opened 2018-04-26 07:39 UTC
Hello,

Since adding this component to our project I can no longer build on azure. Apparently there is some bug with opencollective post install. `npm ls` shows that ngx-infinate-scroll is the only thing depending on that. I get the same error as here:
https://github.com/opencollective/opencollective-cli/issues/8

`npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename
npm ERR! EBUSY: resource busy or locked, rename 'D:\home\site\wwwroot\node_modules\opencollective\dist\bin\opencollective.js.3840949171' -> 'D:\home\site\wwwroot\node_modules\opencollective\dist\bin\opencollective.js'`

The open collective people say they published a lightwieght version:
https://github.com/opencollective/opencollective-cli/issues/3
https://github.com/opencollective/opencollective-postinstall

I dont suppose ngx-infinite-scroll could be updated to use that lightweight version?

**Comment by orizens** [comment] 2018-05-01 15:29
hi @spacem 
as far as i understood, it's not possible to trigger the contribute notice without it.

**Comment by Prashanth-Arralli** [comment] 2018-05-06 16:33
@spacem Found any solution for this problem ?

**Comment by spacem** [comment] 2018-05-10 00:49
Really it is Microsoft's fault since their file pointers are weird. Or maybe it is their directory entries? In other operating systems renaming a directory entry does not require a lock on the file but that is how windows has always been so I guess node.js applications are not multi-platform by default.

I do feel the open collective people are partially to blame. I don't donate financially to open source but I don't think much of companies that take a cut of donations. At least they made the postinstall version but not sure what orizens means that it wont trigger the contrib notice. I thought that was the point of it?

There are a few solutions if you hit this same problem:
* Don't deploy your application
* Don't use windows
* Build the application before deployment
* Fork this infinite scroll library and remove the dependency
* Don't use infinite scroll

Those are in my personal order of preference.. ie. for now I choose just not to deploy my application. It is still in development and I am hoping the problem will just go away on its own.

Anyway thanks for the library and feel free to close my issue if you want.

**Comment by bharathmuppa** [comment] 2018-05-21 23:20
@orizens If that is not a bug then what in the world is that? please dont keep it as dependencies please donate to open source world.

**Comment by thescientist13** [comment] 2018-06-11 14:58
Hey @orizens 
There seems to be another [related issue on this as well](https://github.com/orizens/ngx-infinite-scroll/issues/260) and [acknowledgement here](https://github.com/orizens/ngx-infinite-scroll/pull/231#issuecomment-381630254).

In addition to the error about missing `opencollective` the instructions also require [`opencollective setup`](https://github.com/opencollective/opencollective-cli#install) to be run so I can foresee this not quite working out the way it might have been intended, in particular for CI servers where this minimal opportunity for manual intervention.  

Is there anyway to improve the developer experience for this?  Let me know, I can help open a PR for whatever a viable solution might be.

**Comment by orizens** [comment] 2018-06-11 16:51
hi @thescientist13 
i have my project http://github.com/orizens/echoes-player deployed from travis-ci without any issues. 
I'de be happy to see a relevant pr which keeps opencollective and address the issue - if the issue can is in this repository. 
btw, @ngrx/store is using the same opencollective - so might be worth checking it out there.

**Comment by thescientist13** [comment] 2018-06-11 21:25
ok, thanks @orizens !

Will be glad to take a look on our end this week and report back (or open a PR) if we can help out!

**Comment by Marcidius** [comment] 2018-07-24 17:31
Any movement on this?

**Comment by thescientist13** [comment] 2018-07-24 18:56
the need to upgrade to the newer version hasn't presented itself to me again, so haven't looked into this unfortunately.

**Comment by jcroll** [comment] 2018-07-26 18:47
@orizens I've been trying to bite my tongue but have been continually running into this error over the past couple weeks after upgrading your package:
```
npm ERR! path /usr/share/frontend/node_modules/opencollective/dist/bin/opencollective.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/share/frontend/node_modules/opencollective/dist/bin/opencollective.js'
```

I foresee having to fork your library if you don't remove this unnecessary dependency, it's hard to justify the development hours working around it. 

There's apparently another solution from opencollective (cli or something) but I read somewhere you didn't like it.

This opencollective thing is a pain in the butt tho, please consider removing it

**Comment by orizens** [comment] 2019-03-10 14:14
fixed with 7.1.0

**Closed by orizens** 2019-03-10 14:14 UTC
Labels: NOT a bug

**Comment by jcroll** [comment] 2019-03-11 15:22
Nice!

**Comment by jcroll** [comment] 2019-05-16 13:08
Confirmed, much better thanks @orizens
